### ISSUE TITLE
Datapoint request

### ISSUE THREAD

**Issue by Rushmed** [pixelit-project/ioBroker.pixelit#276]
Hi.

Pls. provide the followig DPs in the adapter:

- button press (/release)
- global text scroll speed
- show_clock options (switching, color...)

Thanks in further!

**Comment by o0shojo0o** [comment]
Hi, 
unfortunately the DPs for button press can't be added so easily because the adapter currently doesn't use the websocket connection but polls the rest API that would have to be reprogrammed first.

**Comment by o0shojo0o** [comment]
In the current git version i have now switched the connection to websocket, so i could also add the buttons as datapoints now.
However, the current not yet published released version 1.0.0 of the Pixelit is also required.

**Comment by Rushmed** [comment]
Just let me know if you got stuff to test for me!

**Comment by o0shojo0o** [comment]
I have just released [PixelIt 1.0.0](https://github.com/o0shojo0o/PixelIt/releases/tag/1.0.0), and also ioBroker.pixelit release 0.1.0 is pushed beta repo. 
There are now the button data points available.

**Comment by Rushmed** [comment]
Would be nice to have a SleepMode button.
Thanks in further!

**Comment by o0shojo0o** [comment]
> * lobal text scroll speed

This makes no sense in the adapter, since it is a global setting and also requires a complete restart of the PixelIt each time.

> * show_clock options (switching, color...)

If you want to display something more complex you can do this with the datapoint ext_message -> [Dokumention](https://pixelit-project.github.io/api.html#clock)

**Comment by o0shojo0o** [comment]
[sleep_mode state](https://github.com/pixelit-project/ioBroker.pixelit/commit/9305e0f955c9a0695d255e588b07dc5588f4943f) available in version 0.2.0.

**Comment by Rushmed** [comment]
Great, ur hyperstellar fast!
I installed it. Its working. Thanks!
