### ISSUE TITLE
"Blocked" area for Icons when sending pixelit.0.message

### ISSUE THREAD

**Issue by Rushmed** [pixelit-project/ioBroker.pixelit#486]
Hi.

Probably this is not a bug.

Up to Pixelit firmware version 2.2.0 I was able to to send messages without an icon in front.
I just did not set the icon. For example:
`Miau! ;255,255,255`
Since v2.3.0 an 8x8 area on the left side is blocked:
![image](https://github.com/pixelit-project/ioBroker.pixelit/assets/59259796/33711943-e21f-4269-8b9e-5fd63428bf04)
I can set an icon to be displayed there but I dont want to have an icon. I`d like to have full screen text scrolling.

**Comment by o0shojo0o** [comment]
@foorschtbar I think you still have a problem with the current customisation of the latest firmware.

This is the JSON that the adpter creates for this display :
```json
{
        "text":{
            "textString": "Miau!",
            "bigFont": false,
            "scrollText":"auto",
            "scrollTextDelay":50,
            "centerText":false,
            "position":{
                "x":8,
                "y":1
            },
            "color":{
                "r":255,
                "g":255,
                "b":255
            }
        }
```

**Comment by foorschtbar** [comment]
Works for me :(

![grafik](https://github.com/pixelit-project/ioBroker.pixelit/assets/10727275/cfdf9195-0bdd-4322-8e01-b88114651686)

**Comment by Rushmed** [comment]
PLS try "Miau, Miau!"

**Comment by foorschtbar** [comment]
![grafik](https://github.com/pixelit-project/ioBroker.pixelit/assets/10727275/225dd3b2-f2c9-4ff5-8a8a-9bb336a6794d)

Yes, now i see it. The problem is the text position: 8 pixel from left side. The "new" behavior is that the text doenst scroll over the configured position. 

@o0shojo0o The IoBroker Adapter need an option to adjust the position, if the 8,1 is fixed.

**Comment by o0shojo0o** [comment]
Please test the current Git version

**Comment by Rushmed** [comment]
Current Git version works as expected. Thanks!
